# Generated by Django 2.2.2 on 2019-06-10 07:40

from django.db import migrations, models
import videoapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField(blank=True, max_length=250)),
                ('file', models.FileField(upload_to='', validators=[videoapp.validators.validate_file_extension, videoapp.validators.validate_file_size])),
            ],
        ),
    ]
