# Generated by Django 2.2.2 on 2019-06-05 20:39

from django.db import migrations, models
import videoapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_auto_20190605_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='', validators=[videoapp.validators.validate_file_extension, videoapp.validators.validate_file_size]),
        ),
    ]
