# Generated by Django 2.2.2 on 2019-06-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_auto_20190605_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
