# Generated by Django 2.2.2 on 2019-06-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0004_auto_20190605_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videofile',
            new_name='file',
        ),
    ]
